# Collection of all functions reading and writing to hdf5 files

#
# General head section of any file within this module 
#

#
# Using statements
#
using HDF5

#
# Include statements
#

#
# Export statements
#
export read_hdf5_output_file

#
# Definition of global variables
#

#
# Specific section for this file
#

# A function to create the hdf5 file with all groups and datasets
function create_hdf5_output_file(inputfile_path)

    # Use the input file path to generate the output file name and path
    file_name = basename(inputfile_path)
    dir_name = dirname(inputfile_path)

    file_prefix = ""
    outputfile_path = ""
    if occursin(".", file_name)
        file_prefix = split(file_name,".")[1]
    else
        file_prefix = file_name
    end
    outputfile_path = joinpath(dir_name, file_prefix * ".h5")

    # Check whether the file already exists
    if isfile(outputfile_path)
        println("The following file already exists: " * outputfile_path)
        println("Please delete this file to start a new simulation.")
        error("Output File Error")
    end

    # Generate the general structure of the hdf5 file
    # Open the file
    hdf5_id = h5open(outputfile_path, "cw")

    # Add attributes to the file
    attributes(hdf5_id)["info"] = "HDF5 output file generated by RSA code"
    attributes(hdf5_id)["url"] = ""
    attributes(hdf5_id)["version"] = "0.6"
    attributes(hdf5_id)["date"] = string(now())
    attributes(hdf5_id)["threads"] = string(Threads.nthreads())
    attributes(hdf5_id)["cpuinfo"] = Base.Sys.cpu_info()[1].model
    attributes(hdf5_id)["generations"] = "1"

    # Generate groups
    Nlevel1 = 3
    level1_groups = ["inputfile-info", "preparation-info", "run-info"]
    for groups_id in 1:Nlevel1
        create_group(hdf5_id, level1_groups[groups_id])
    end

    # Add attributes to these groups
    group_id = hdf5_id["inputfile-info"]
    attributes(group_id)["info"] = "This group contains all information obtained and generated based on the user input filt. Every molecule and every grid is stored in a separate group."
    group_id = hdf5_id["preparation-info"]
    attributes(group_id)["info"] = "This group contains all distance matrices generated based on the input file. These matrices are used to define possible outcomes of any event. Every run is stored as a group."
    group_id = hdf5_id["run-info"]
    attributes(group_id)["info"] = "This group contains the results of every RSA simulation. Every RSA simulation is stored in a single group."

    # Generate the subgroups for generation-1
    for groups_id in 1:Nlevel1
        create_group(hdf5_id, level1_groups[groups_id]*"/generation-1")
    end
   
    # Close the file
    close(hdf5_id)

    # Return the file name
    return outputfile_path

end

# A function to create subgroups for a new generation
function create_hdf5_restart_subgroups(hdf5_file, generation)
    
    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * hdf5_file)
        error("Restart Error")
    end

    # Open the file
    hdf5_id = h5open(hdf5_file, "cw")

    # Generate the subgroups for generation-X
    level1_groups = ["inputfile-info", "preparation-info", "run-info"]   
    for groups_id in level1_groups
        subgroup = groups_id * "/generation-" * string(generation)
        if haskey(hdf5_id, subgroup)
            close(hdf5_id)
            println("The restart target group already exists: " * subgroup)
            error("Restart Error")
        end
        create_group(hdf5_id, subgroup)
    end

    # Close the file
    close(hdf5_id)

end

# A function to read the number of generations currently stored in an HDF5 output file
function read_hdf5_number_of_generations(hdf5_file)
    hdf5_id = h5open(hdf5_file, "r")
        generation = parse(Int64, read_attribute(hdf5_id, "generations"))
    close(hdf5_id)
    return generation
end

# A function to change the number of generations currently stored in an HDF5 output file
function reset_hdf5_number_of_generations(hdf5_file, generation)
    hdf5_id = h5open(hdf5_file, "cw")
        delete_attribute(hdf5_id, "generations")
        attributes(hdf5_id)["generations"] = string(generation)
    close(hdf5_id)
end

# A function to write input file information to an hdf5 file
function write_hdf5_input_information(hdf5_file, generation, Nmolecules, molecules, Ngrids, grids, lattice, events)

    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * hdf5_file)
        error("Output File Error")
    end

    # Open the file
    hdf5_id = h5open(hdf5_file, "cw")

    # Get the group id 
    group_id = hdf5_id["inputfile-info/generation-"*string(generation)]

    # Write the datasets without subgroups
    group_id["number-of-molecules"] = Nmolecules
    group_id["number-of-grids"] = Ngrids

    # Write the lattice
    write_hdf5_lattice(lattice, group_id)

    # Write the molecules
    write_hdf5_molecules(Nmolecules, molecules, group_id)

    # Write the grids
    write_hdf5_grids(Ngrids, grids, group_id)

    # Write the events
    write_hdf5_events(events, group_id)

    # Close the file
    close(hdf5_id)
    
end

# A function to write lattice information to a hdf5 file
# The file must be open prior to calling this function
function write_hdf5_lattice(lattice, group_id)

    # Generate the group
    create_group(group_id, "lattice")
    lattice_id = group_id["lattice"]

    # Write the information
    lattice_id["dimension"] = lattice.dimension
    lattice_id["vectors"] = lattice.vectors
    lattice_id["transx"] = lattice.transx
    lattice_id["transy"] = lattice.transy
    lattice_id["Ncellx"] = lattice.Ncellx
    lattice_id["Ncelly"] = lattice.Ncelly
    lattice_id["transvectors"] = lattice.transvectors
    lattice_id["inversevectors"] = lattice.inversevectors

end

# A function to read lattice information from a hdf5 file
# The file must be open prior to calling this function
function read_hdf5_lattice(group_id)

    # Select the group
    lattice_id = group_id["lattice"]

    # Generate the struct
    lattice = lattice_struct()

    # Read the information
    lattice.dimension = read(lattice_id, "dimension")
    lattice.vectors = read(lattice_id, "vectors")
    lattice.transx = read(lattice_id, "transx")
    lattice.transy = read(lattice_id, "transy")
    lattice.Ncellx = read(lattice_id, "Ncellx") 
    lattice.Ncelly = read(lattice_id, "Ncelly")
    lattice.transvectors = read(lattice_id, "transvectors")
    lattice.inversevectors = read(lattice_id, "inversevectors")

    # Return results
    return lattice
    
end

# A function to write molecule information to a hdf5 file
# The file must be open prior to calling this function
function write_hdf5_molecules(Nmolecules, molecules, group_id)
    
    # Loop over all molecules
    for molecule_id in 1:Nmolecules

        # Generate the group
        create_group(group_id, "molecule-"*string(molecule_id))
        molecule_group_id = group_id["molecule-"*string(molecule_id)]

        # Write the information
        molecule_group_id["label"] = molecules[molecule_id].label
        molecule_group_id["grids"] = molecules[molecule_id].grids
        molecule_group_id["fixpointtype"] = molecules[molecule_id].fixpointtype
        molecule_group_id["fixpointatoms"] = molecules[molecule_id].fixpointatoms
        molecule_group_id["fixpoint"] = molecules[molecule_id].fixpoint
        molecule_group_id["rotationmodus"] = molecules[molecule_id].rotationmodus
        molecule_group_id["rotationangle"] = molecules[molecule_id].rotationangle
        molecule_group_id["rotationvalues"] = molecules[molecule_id].rotationvalues
        molecule_group_id["Nrotations"] = molecules[molecule_id].Nrotations
        molecule_group_id["rotations"] = molecules[molecule_id].rotations
        molecule_group_id["coordinate_path"] = molecules[molecule_id].coordinate_path
        molecule_group_id["Natoms"] = molecules[molecule_id].Natoms
        molecule_group_id["elements"] = molecules[molecule_id].elements
        molecule_group_id["elements_sorted"] = molecules[molecule_id].elements_sorted
        molecule_group_id["dimension"] = molecules[molecule_id].dimension
        molecule_group_id["coordinates"] = molecules[molecule_id].coordinates
        molecule_group_id["coordinates_sorted"] = molecules[molecule_id].coordinates_sorted
        molecule_group_id["maxradius"] = molecules[molecule_id].maxradius
        molecule_group_id["radii"] = molecules[molecule_id].radii
        molecule_group_id["radii_sorted"] = molecules[molecule_id].radii_sorted

        # Write information needing their own group
        create_group(molecule_group_id, "coordinates_rotated")
        rotations_group_id = molecule_group_id["coordinates_rotated"]
        for rotation_id in 1:molecules[molecule_id].Nrotations
            rotations_group_id["rotation-"*string(rotation_id)] = molecules[molecule_id].coordinates_rotated[rotation_id]
        end

    end

end

# A function to read molecule information from a hdf5 file
# The file must be open prior to calling this function
function read_hdf5_molecules(Nmolecules, group_id)
    
    # Generate the struct
    molecules = Vector{molecule_struct}(undef, 0)

    # Loop over all molecules
    for molecule_id in 1:Nmolecules

        # Select the group
        molecule_group_id = group_id["molecule-"*string(molecule_id)]

        # Generate the struct
        molecule = molecule_struct()

        # Read the information
        molecule.label = read(molecule_group_id, "label")
        molecule.grids = read(molecule_group_id, "grids")
        molecule.fixpointtype = read(molecule_group_id, "fixpointtype")
        molecule.fixpointatoms = read(molecule_group_id, "fixpointatoms")
        molecule.fixpoint = read(molecule_group_id, "fixpoint")
        molecule.rotationmodus = read(molecule_group_id, "rotationmodus")
        molecule.rotationangle = read(molecule_group_id, "rotationangle")
        molecule.rotationvalues = read(molecule_group_id, "rotationvalues")
        molecule.Nrotations = read(molecule_group_id, "Nrotations")
        molecule.rotations = read(molecule_group_id, "rotations")
        molecule.coordinate_path = read(molecule_group_id, "coordinate_path")
        molecule.Natoms = read(molecule_group_id, "Natoms")
        molecule.elements = read(molecule_group_id, "elements")
        molecule.elements_sorted = read(molecule_group_id, "elements_sorted")
        molecule.dimension = read(molecule_group_id, "dimension")
        molecule.coordinates = read(molecule_group_id, "coordinates")
        molecule.coordinates_sorted = read(molecule_group_id, "coordinates_sorted")
        molecule.maxradius = read(molecule_group_id, "maxradius")
        molecule.radii = read(molecule_group_id, "radii")
        molecule.radii_sorted = read(molecule_group_id, "radii_sorted")

        # Read information needing their own group
        rotations_group_id = molecule_group_id["coordinates_rotated"]
        molecule.coordinates_rotated = Vector{Matrix{Float64}}(undef, molecule.Nrotations)
        for rotation_id in 1:molecule.Nrotations
            molecule.coordinates_rotated[rotation_id] = read(rotations_group_id, "rotation-"*string(rotation_id))
        end

        # Add the molecule struct to the vector of structs
        push!(molecules, molecule)

    end

    # Return the result
    return molecules

end

# A function to write grid information to a hdf5 file
# The file must be open prior to calling this function
function write_hdf5_grids(Ngrids, grids, group_id)
    
    # Loop over all grids
    for grid_id in 1:Ngrids

        # Generate the group
        create_group(group_id, "grid-"*string(grid_id))
        grid_group_id = group_id["grid-"*string(grid_id)]

        # Write the information
        grid_group_id["label"] = grids[grid_id].label
        grid_group_id["Nuniquepoints"] = grids[grid_id].Nuniquepoints
        grid_group_id["uniquepoints"] = grids[grid_id].uniquepoints
        grid_group_id["dimension"] = grids[grid_id].dimension
        grid_group_id["Npoints"] = grids[grid_id].Npoints
        grid_group_id["points"] = grids[grid_id].points
        grid_group_id["mapping"] = grids[grid_id].mapping

    end

end

# A function to read grid information from a hdf5 file
# The file must be open prior to calling this function
function read_hdf5_grids(Ngrids, group_id)
    
    # Generate the struct
    grids = Vector{grid_struct}(undef,0)

    # Loop over all grids
    for grid_id in 1:Ngrids

        # Generate the struct
        grid = grid_struct()

        # Select the group
        grid_group_id = group_id["grid-"*string(grid_id)]

        # Read the information
        grid.label = read(grid_group_id, "label")
        grid.Nuniquepoints = read(grid_group_id, "Nuniquepoints")
        grid.uniquepoints = read(grid_group_id, "uniquepoints")
        grid.dimension = read(grid_group_id, "dimension")
        grid.Npoints = read(grid_group_id, "Npoints")
        grid.points = read(grid_group_id, "points")
        grid.mapping = read(grid_group_id, "mapping")

        # Add the grid to the struct vector
        push!(grids, grid)

    end

    # Return the results
    return grids

end

# A function to write event information to a hdf5 file
# The file must be open prior to calling this function
function write_hdf5_events(events, group_id)

    # Generate the group
    create_group(group_id, "events")
    events_id = group_id["events"]

    # Store datasets
    events_id["steps"] = events.steps
    events_id["break_steps"] = events.break_steps
    events_id["coverage_convergence"] = events.coverage_convergence
    events_id["break_convergence"] = events.break_convergence
    events_id["Nforce_adsorption"] = events.Nforce_adsorption
    events_id["force_adsorption"] = events.force_adsorption
    events_id["weigth_scale"] = events.weigth_scale
    events_id["force_weigth_scale"] = events.force_weigth_scale
    events_id["overlap2d"] = events.overlap2d
    events_id["overlap3d"] = events.overlap3d
    events_id["Nevents"] = events.Nevents
    events_id["Nadsorptions"] = events.Nadsorptions
    events_id["Ndiffusions"] = events.Ndiffusions
    events_id["Nrotations"] = events.Nrotations
    events_id["Nconformers"] = events.Nconformers
    events_id["restart_flag"] = events.restart_flag
    events_id["restart_generation"] = events.restart_generation
    events_id["restart_runs"] = events.restart_runs
    events_id["restart_file"] = events.restart_file

    create_group(events_id, "adsorptions")
    sub_events_id = events_id["adsorptions"]
    for ads_id in 1:events.Nadsorptions    
        create_group(sub_events_id, "adsorption-"*string(ads_id))
        adsorption_events_id = sub_events_id["adsorption-"*string(ads_id)]
        adsorption_events_id["molecule"] = events.adsorptions[ads_id].molecule
        adsorption_events_id["grid"] = events.adsorptions[ads_id].grid
        adsorption_events_id["weigth"] = events.adsorptions[ads_id].weigth
    end

    create_group(events_id, "rotations")
    sub_events_id = events_id["rotations"]
    for rot_id in 1:events.Nrotations
        create_group(sub_events_id, "rotation-"*string(rot_id))
        rotation_events_id = sub_events_id["rotation-"*string(rot_id)]
        rotation_events_id["molecule"] = events.rotations[rot_id].molecule
        rotation_events_id["grid"] = events.rotations[rot_id].grid
        rotation_events_id["weigth"] = events.rotations[rot_id].weigth
    end

    create_group(events_id, "diffusions")
    sub_events_id = events_id["diffusions"]
    for dif_id in 1:events.Ndiffusions
        create_group(sub_events_id, "diffusion-"*string(dif_id))
        diffusion_events_id = sub_events_id["diffusion-"*string(dif_id)]
        diffusion_events_id["molecule"] = events.diffusions[dif_id].molecule
        diffusion_events_id["grid_start"] = events.diffusions[dif_id].grid_start
        diffusion_events_id["grid_end"] = events.diffusions[dif_id].grid_end
        diffusion_events_id["weigth"] = events.diffusions[dif_id].weigth
        diffusion_events_id["radius"] = events.diffusions[dif_id].radius
    end

    create_group(events_id, "conformers")
    sub_events_id = events_id["conformers"]
    for con_id in 1:events.Nconformers
        create_group(sub_events_id, "conformer-"*string(con_id))
        conformer_events_id = sub_events_id["conformer-"*string(con_id)]
        conformer_events_id["molecule_start"] = events.conformers[con_id].molecule_start
        conformer_events_id["molecule_end"] = events.conformers[con_id].molecule_end
        conformer_events_id["grid"] = events.conformers[con_id].grid
        conformer_events_id["weigth"] = events.conformers[con_id].weigth
    end
    
end

# A function to read event information from a hdf5 file
# The file must be open prior to calling this function
function read_hdf5_events(group_id)

    # Select the group
    events_id = group_id["events"]

    # Generate the events struct
    events = events_struct()

    # Read datasets
    events.steps = read(events_id, "steps")
    events.break_steps = read(events_id, "break_steps")
    events.coverage_convergence = read(events_id, "coverage_convergence")
    events.break_convergence = read(events_id, "break_convergence")
    events.Nforce_adsorption = read(events_id, "Nforce_adsorption")
    events.force_adsorption = read(events_id, "force_adsorption")
    events.weigth_scale = read(events_id, "weigth_scale")
    events.force_weigth_scale = read(events_id, "force_weigth_scale")
    events.overlap2d = read(events_id, "overlap2d")
    events.overlap3d = read(events_id, "overlap3d")
    events.Nevents = read(events_id, "Nevents")
    events.Nadsorptions = read(events_id, "Nadsorptions")
    events.Ndiffusions = read(events_id, "Ndiffusions")
    events.Nrotations = read(events_id, "Nrotations")
    events.Nconformers = read(events_id, "Nconformers")
    events.restart_flag = read(events_id, "restart_flag")
    events.restart_generation = read(events_id, "restart_generation")
    events.restart_runs = read(events_id, "restart_runs")
    events.restart_file = read(events_id, "restart_file")

    # Read subgroups with their datasets
    sub_events_id = events_id["adsorptions"]
    for ads_id in 1:events.Nadsorptions    
        adsorption_events_id = sub_events_id["adsorption-"*string(ads_id)]
        subevent = event_adsorption_struct()
        subevent.molecule = read(adsorption_events_id, "molecule")
        subevent.grid = read(adsorption_events_id, "grid")
        subevent.weigth = read(adsorption_events_id, "weigth")
        push!(events.adsorptions, subevent)
    end

    sub_events_id = events_id["rotations"]
    for rot_id in 1:events.Nrotations
        rotation_events_id = sub_events_id["rotation-"*string(rot_id)]
        subevent = event_rotation_struct()
        subevent.molecule = read(rotation_events_id, "molecule")
        subevent.grid = read(rotation_events_id, "grid")
        subevent.weigth = read(rotation_events_id, "weigth")
        push!(events.rotations, subevent)
    end

    sub_events_id = events_id["diffusions"]
    for dif_id in 1:events.Ndiffusions
        diffusion_events_id = sub_events_id["diffusion-"*string(dif_id)]
        subevent = event_diffusion_struct()
        subevent.molecule = read(diffusion_events_id, "molecule")
        subevent.grid_start = read(diffusion_events_id, "grid_start")
        subevent.grid_end = read(diffusion_events_id, "grid_end")
        subevent.weigth = read(diffusion_events_id, "weigth")
        subevent.radius = read(diffusion_events_id, "radius")
        push!(events.diffusions, subevent)
    end

    sub_events_id = events_id["conformers"]
    for con_id in 1:events.Nconformers
        conformer_events_id = sub_events_id["conformer-"*string(con_id)]
        subevent = event_conformer_change_struct()
        subevent.molecule_start = read(conformer_events_id, "molecule_start")
        subevent.molecule_end = read(conformer_events_id, "molecule_end")
        subevent.grid = read(conformer_events_id, "grid")
        subevent.weigth = read(conformer_events_id, "weigth")
        push!(events.conformers, subevent)
    end
    
    # Return the results
    return events

end

# A function to read an hdf5 file to get all input information
function read_hdf5_input_information(hdf5_file, generation)
    
    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * outputfile_path)
        error("Input Reading Error")
    end

    # Open the file
    hdf5_id = h5open(hdf5_file, "r")

    # Get the group id 
    group_id = hdf5_id["inputfile-info/generation-"*string(generation)]

    # Read the datasets without subgroups
    Nmolecules = read(group_id, "number-of-molecules") 
    Ngrids = read(group_id, "number-of-grids")

    # Read the lattice
    lattice = read_hdf5_lattice(group_id)

    # Read the molecules
    molecules = read_hdf5_molecules(Nmolecules, group_id)

    # Read the grids
    grids = read_hdf5_grids(Ngrids, group_id)

    # Read the events
    events = read_hdf5_events(group_id)

    # Close the file
    close(hdf5_id)

    # Return input information
    return Nmolecules, molecules, Ngrids, grids, lattice, events

end

# A function to write preparation information to an hdf5 file
function write_preparation_information(hdf5_file, generation, Ngrids, grids, lattice, Nmolecules, molecules, unit_cell_gridpoints_difference, translation_distance_vectors, rotation_difference_matrices, Affected_Points_Rotations, rate_constants_info, neighbour_list)
    
    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * outputfile_path)
        error("Output File Error")
    end

    # Open the file
    hdf5_id = h5open(hdf5_file, "cw")

    # Get the group id 
    main_id = hdf5_id["preparation-info"]["generation-"*string(generation)]

    # Write gridpoint difference vectors
    tmp_matrix = Matrix{Float64}(undef, 3, 0)
    for grid_B_id in 1:Ngrids
        for grid_A_id in 1:Ngrids

            # Reduce all submatrices to one large matrix
            tmp_matrix_2 = unit_cell_gridpoints_difference[grid_A_id, grid_B_id]
            reduced_matrix = reduce(hcat, tmp_matrix_2)
            tmp_matrix = hcat(tmp_matrix, reduced_matrix)

        end
    end
    main_id["gridpoints-difference"] = tmp_matrix

    # Write the translation distance vectors
    # Reduce to one matrix
    reduced_matrix = reduce(hcat, translation_distance_vectors)
    main_id["translation-vectors"] = reduced_matrix

    # Write the rotation difference vectors
    tmp_matrix = Matrix{Float64}(undef, 3, 0)
    # Loop over molecules
    for molecule_B_id in 1:Nmolecules
        for molecule_A_id in 1:Nmolecules

            # Reduce to one matrix
            tmp_matrix_2 = rotation_difference_matrices[molecule_A_id, molecule_B_id]
            reduced_matrix1 = reduce(hcat, tmp_matrix_2)
            reduced_matrix2 = reduce(hcat, reduced_matrix1)
            tmp_matrix = hcat(tmp_matrix, reduced_matrix2)


        end
    end
    main_id["rotation-differences"] = tmp_matrix

    # Write the affected gridpoints matrices
    create_group(main_id, "affected-points")
    group_id = main_id["affected-points"]
    levels = [false, false, false]
    # Loop over molecules
    molec_subgroup_id = ""
    grid_subgroup_id = ""
    point_subgroup_id = ""
    for molecule_id in 1:Nmolecules

        # Set level 1 to false
        levels[1] = false

        # Loop over gridtypes
        for grid_id in 1:Ngrids

            # Set level 2 to false
            levels[2] = false

            # Loop over gridpoints
            for point_id in 1:grids[grid_id].Nuniquepoints

                # Set level 3 to false
                levels[3] = false

                # Loop over rotations
                for rotation_id in 1:molecules[molecule_id].Nrotations

                    if levels[3] == false

                        # Check whether element is empty
                        if ! isempty(Affected_Points_Rotations[molecule_id][grid_id][point_id][rotation_id])

                            if levels[1] == false
                                levels[1] = true
                                # Create subgroup
                                molec_subgroup_name = "molecule-vector-" * string(molecule_id)
                                create_group(group_id, molec_subgroup_name)
                                molec_subgroup_id = group_id[molec_subgroup_name]
                            end
                            if levels[2] == false
                                levels[2] = true
                                # Create subgroup
                                grid_subgroup_name = "grid-vector-" * string(grid_id)
                                create_group(molec_subgroup_id, grid_subgroup_name)
                                grid_subgroup_id = molec_subgroup_id[grid_subgroup_name]
                            end
                            if levels[3] == false
                                levels[3] = true
                                # Create subgroup
                                point_subgroup_name = "point-vector-" * string(point_id)
                                create_group(grid_subgroup_id, point_subgroup_name)
                                point_subgroup_id = grid_subgroup_id[point_subgroup_name]
                            end

                            # Create dataset
                            dataset_name = "rotation-vector-" * string(rotation_id)
                            point_subgroup_id[dataset_name] = Affected_Points_Rotations[molecule_id][grid_id][point_id][rotation_id]
                            continue

                        end

                    end

                    if ! isempty(Affected_Points_Rotations[molecule_id][grid_id][point_id][rotation_id])
                        
                        # Create dataset
                        dataset_name = "rotation-vector-" * string(rotation_id)
                        point_subgroup_id[dataset_name] = Affected_Points_Rotations[molecule_id][grid_id][point_id][rotation_id]
                    
                    end

                end

            end

        end

    end

    # Write the neighbour list
    create_group(main_id, "neighbour-list")
    group_id = main_id["neighbour-list"]
    # Loop over starting grid
    levels = [false, false, false]
    sgrid_subgroup_id = ""
    spoint_subgroup_id =""
    molec_subgroup_id = ""
    for start_grid_id in 1:Ngrids

        # Set level 1 to false
        levels[1] = false

        # Loop over starting point
        for start_point_id in 1:grids[start_grid_id].Nuniquepoints

            # Set level 2 to false
            levels[2] = false

            # Loop over molecules
            for molecule_id in 1:Nmolecules

                # Set level 3 to false
                levels[3] = false

                # Loop over end grid
                for end_grid_id in 1:Ngrids

                    if levels[3] == false

                        # Check whether element is empty
                        if ! isempty(neighbour_list[start_grid_id][start_point_id][molecule_id][end_grid_id])

                            if levels[1] == false
                                levels[1] = true
                                # Create subgroup
                                sgrid_subgroup_name = "start-grid-" * string(start_grid_id)
                                create_group(group_id, sgrid_subgroup_name)
                                sgrid_subgroup_id = group_id[sgrid_subgroup_name]
                            end
                            if levels[2] == false
                                levels[2] = true
                                # Create subgroup
                                spoint_subgroup_name = "start-point-" * string(start_point_id)
                                create_group(sgrid_subgroup_id, spoint_subgroup_name)
                                spoint_subgroup_id = sgrid_subgroup_id[spoint_subgroup_name]
                            end
                            if levels[3] == false
                                levels[3] = true
                                # Create subgroup
                                molec_subgroup_name = "molecule-" * string(molecule_id)
                                create_group(spoint_subgroup_id, molec_subgroup_name)
                                molec_subgroup_id = spoint_subgroup_id[molec_subgroup_name]
                            end

                            # Create dataset
                            dataset_name = "end-grid-" * string(end_grid_id)
                            molec_subgroup_id[dataset_name] = neighbour_list[start_grid_id][start_point_id][molecule_id][end_grid_id]
                            continue

                        end

                    end

                    if ! isempty(neighbour_list[start_grid_id][start_point_id][molecule_id][end_grid_id])

                        # Create dataset
                        dataset_name = "end-grid-" * string(end_grid_id)
                        molec_subgroup_id[dataset_name] = neighbour_list[start_grid_id][start_point_id][molecule_id][end_grid_id]

                    end

                end

            end

        end

    end

    # Write rate constants subgroup
    create_group(main_id, "rate-constants")
    subgroup_id = main_id["rate-constants"]
    subgroup_id["ads"] = rate_constants_info.ads
    subgroup_id["rot"] = rate_constants_info.rot
    subgroup_id["dif"] = rate_constants_info.dif
    subgroup_id["dif_rad"] = rate_constants_info.dif_rad
    subgroup_id["con"] = rate_constants_info.con
    
    # Close the file
    close(hdf5_id)

end

# A function to read preparation information from an hdf5 file
function read_preparation_information(hdf5_file, generation, Ngrids, grids, lattice, Nmolecules, molecules)
    
    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * outputfile_path)
        error("Output File Error")
    end

    # Open the file
    hdf5_id = h5open(hdf5_file, "r")

    # Get the group id 
    main_id = hdf5_id["preparation-info/run-"*string(generation)]

    # Read gridpoint difference vectors
    tmp_read_matrix = read(main_id, "gridpoints-difference")
    unit_cell_gridpoints_difference = Matrix{Matrix{Vector{Float64}}}(undef, Ngrids, Ngrids)
    id_count = 0
    # Loop over gridpoints
    for grid_B_id in 1:Ngrids
        for grid_A_id in 1:Ngrids
            
            # Generate tmp matrix
            gridpoints_difference_matrix = Matrix{Vector{Float64}}(undef, grids[grid_A_id].Nuniquepoints, grids[grid_B_id].Nuniquepoints)

            # Read in the values
            for column_id in 1:grids[grid_B_id].Nuniquepoints
                for row_id in 1:grids[grid_A_id].Nuniquepoints
                    id_count += 1
                    gridpoints_difference_matrix[row_id, column_id] = tmp_read_matrix[:,id_count]
                end
            end

            # Store in the final matrix
            unit_cell_gridpoints_difference[grid_A_id, grid_B_id] = gridpoints_difference_matrix

        end
    end

    # Read translation vectors
    translation_distance_vectors = Matrix{Vector{Float64}}(undef, lattice.transx + 1, lattice.transy + 1)
    tmp_read_matrix = read(main_id, "translation-vectors") 
    # Read in the values
    id_count = 0
    for column_id in 1:lattice.transy + 1
        for row_id in 1:lattice.transx + 1
            id_count += 1
            translation_distance_vectors[row_id, column_id] = tmp_read_matrix[:,id_count]
        end
    end

    # Read rotation difference vectors
    # Create the initial matrix to store all results
    rotation_difference_matrices = Matrix{Matrix{Matrix{Vector{Float64}}}}(undef, Nmolecules, Nmolecules)
    id_count = 0
    tmp_read_matrix = read(main_id, "rotation-differences") 
    # First loop over the molecules
    for molecule_B_id in 1:Nmolecules
        for molecule_A_id in 1:Nmolecules

            # Generate tmp matrix
            tmp_molecule_difference_matrix = Matrix{Matrix{Vector{Float64}}}(undef, molecules[molecule_A_id].Nrotations, molecules[molecule_B_id].Nrotations)

            # Loop over rotations
            for rotation_B_id in 1:molecules[molecule_B_id].Nrotations
                for rotation_A_id in 1:molecules[molecule_A_id].Nrotations
                        
                    # Define blank matrix
                    tmp_matrix = Matrix{Vector{Float64}}(undef, molecules[molecule_A_id].Natoms, molecules[molecule_B_id].Natoms)
            
                    # Read its values
                    for atom_B_id in 1:molecules[molecule_B_id].Natoms
                        for atom_A_id in 1:molecules[molecule_A_id].Natoms
                            id_count += 1
                            tmp_matrix[atom_A_id, atom_B_id] = tmp_read_matrix[:,id_count]
                        end
                    end

                    # Store it in the final matrix
                    tmp_molecule_difference_matrix[rotation_A_id, rotation_B_id] = tmp_matrix

                end
            end

            # Store in the final matrix
            rotation_difference_matrices[molecule_A_id, molecule_B_id] = tmp_molecule_difference_matrix

        end
    end

    # Read the affected points
    # Create an empty array to store all values
    Affected_Points_Rotations = Vector{Vector{Vector{Vector{Matrix{Int64}}}}}(undef,Nmolecules)
    for molecule_id in 1:Nmolecules
        Affected_Points_Rotations[molecule_id] = Vector{Vector{Vector{Matrix{Int64}}}}(undef,Ngrids)
        for grid_id in 1:Ngrids
            Affected_Points_Rotations[molecule_id][grid_id] = Vector{Vector{Matrix{Int64}}}(undef, grids[grid_id].Nuniquepoints)
            for unique_grid_id in 1:grids[grid_id].Nuniquepoints
                Affected_Points_Rotations[molecule_id][grid_id][unique_grid_id] = Vector{Matrix{Int64}}(undef, molecules[molecule_id].Nrotations)
                for rotation_id in 1:molecules[molecule_id].Nrotations
                    Affected_Points_Rotations[molecule_id][grid_id][unique_grid_id][rotation_id] = Matrix{Int64}(undef, 4 ,0)
                end
            end
        end
    end

    # Read in the values 
    group_id = main_id["affected-points"]
    # Loop over molecules
    for molecule_id in 1:Nmolecules

        # Check whether this groups exists
        molec_subgroup_name = "molecule-vector-" * string(molecule_id)
        if ! haskey(group_id, molec_subgroup_name)
            continue
        end
        molec_subgroup_id = group_id[molec_subgroup_name]

        # Loop over gridtypes
        for grid_id in 1:Ngrids

            # Check whether this groups exists
            grid_subgroup_name = "grid-vector-" * string(grid_id)
            if ! haskey(molec_subgroup_id, grid_subgroup_name)
                continue
            end
            grid_subgroup_id = molec_subgroup_id[grid_subgroup_name]

            # Loop over gridpoints
            for point_id in 1:grids[grid_id].Nuniquepoints

                # Check whether this groups exists
                point_subgroup_name = "point-vector-" * string(point_id)
                if ! haskey(grid_subgroup_id, point_subgroup_name)
                    continue
                end
                point_subgroup_id = grid_subgroup_id[point_subgroup_name]

                # Loop over rotations
                for rotation_id in 1:molecules[molecule_id].Nrotations

                    # Check whether this dataset exists
                    dataset_name = "rotation-vector-" * string(rotation_id)
                    if ! haskey(point_subgroup_id, dataset_name)
                        continue
                    end
                    Affected_Points_Rotations[molecule_id][grid_id][point_id][rotation_id] = read(point_subgroup_id, dataset_name)

                end

            end

        end

    end

    # Read the neighbour list
    group_id = main_id["neighbour-list"]
    neighbour_list = Vector{Vector{Vector{Vector{Vector{Int64}}}}}(undef, Ngrids)
    for start_grid_id in 1:Ngrids
        neighbour_list[start_grid_id] = Vector{Vector{Vector{Vector{Int64}}}}(undef, grids[start_grid_id].Nuniquepoints)
        for start_point_id in 1:grids[start_grid_id].Nuniquepoints
            neighbour_list[start_grid_id][start_point_id] = Vector{Vector{Vector{Int64}}}(undef, Nmolecules)
            for molecule_id in 1:Nmolecules
                neighbour_list[start_grid_id][start_point_id][molecule_id] = Vector{Vector{Int64}}(undef, Ngrids)
                for end_grid_id in 1:Ngrids
                    neighbour_list[start_grid_id][start_point_id][molecule_id][end_grid_id] = Vector{Int64}(undef, 0)
                end
            end
        end
    end
    # Loop over starting grid
    for start_grid_id in 1:Ngrids

        # Check whether this groups exists
        sgrid_subgroup_name = "start-grid-" * string(start_grid_id)
        if ! haskey(group_id, sgrid_subgroup_name)
            continue
        end
        sgrid_subgroup_id = group_id[sgrid_subgroup_name]

        # Loop over starting point
        for start_point_id in 1:grids[start_grid_id].Nuniquepoints

            # Check whether this groups exists
            spoint_subgroup_name = "start-point-" * string(start_point_id)
            if ! haskey(sgrid_subgroup_id, spoint_subgroup_name)
                continue
            end
            spoint_subgroup_id = sgrid_subgroup_id[spoint_subgroup_name]

            # Loop over molecules
            for molecule_id in 1:Nmolecules

                # Check whether this groups exists
                molec_subgroup_name = "molecule-" * string(molecule_id)
                if ! haskey(spoint_subgroup_id, molec_subgroup_name)
                    continue
                end
                molec_subgroup_id = spoint_subgroup_id[molec_subgroup_name]

                # Loop over end grid
                for end_grid_id in 1:Ngrids

                    # Check whether this dataset exists
                    dataset_name = "end-grid-" * string(end_grid_id)
                    if ! haskey(molec_subgroup_id, dataset_name)
                        continue
                    end
                    neighbour_list[start_grid_id][start_point_id][molecule_id][end_grid_id] = read(molec_subgroup_id, dataset_name)

                end

            end

        end

    end

    # Read rate constants subgroup
    group_id = main_id["rate-constants"]
    rate_constants_info = rate_constants_struct()
    rate_constants_info.ads = read(group_id, "ads")
    rate_constants_info.rot = read(group_id, "rot")
    rate_constants_info.dif = read(group_id, "dif")
    rate_constants_info.dif_rad = read(group_id, "dif_rad")
    rate_constants_info.con = read(group_id, "con")
    
    # Close the file
    close(hdf5_id)

    # Return the results
    return unit_cell_gridpoints_difference, translation_distance_vectors, rotation_difference_matrices, Affected_Points_Rotations, neighbour_list, rate_constants_info

end

# A function to write the results of RSA runs
function write_rsa_results(hdf5_file, generation, NRuns, rsa_results)
    
    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * outputfile_path)
        error("Output File Error")
    end

    # Open the file
    hdf5_id = h5open(hdf5_file, "cw")

    # Write the number of performed runs
    main_id = hdf5_id["run-info"]["generation-"*string(generation)]
    main_id["Nruns"] = NRuns

    # Close the file
    close(hdf5_id)


    # Write every rsa run to the hdf5 file
    for run_id in 1:NRuns
        write_hdf5_rsa_run(hdf5_file, generation, run_id, rsa_results[run_id])    
    end
    
end

function write_hdf5_rsa_run(hdf5_file, generation, run_id, rsa_result)

    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * outputfile_path)
        error("Output File Error")
    end

    # Open the file
    hdf5_id = h5open(hdf5_file, "cw")

    # Create the group to store all information
    main_id = hdf5_id["run-info"]["generation-"*string(generation)]
    create_group(main_id, "rsa-run-"*string(run_id))
    group_id = main_id["rsa-run-"*string(run_id)]

    # Generate a tmp matrix to store all elements of the Nevents matrix
    tmp_Nevents = reduce(hcat, rsa_result.Nevents)

    # Write all information
    group_id["randomseed"] = rsa_result.randomseed
    group_id["status"] = rsa_result.status
    group_id["Nsteps"] = rsa_result.Nsteps
    group_id["stepinfo"] = rsa_result.stepinfo
    group_id["Nevents"] = tmp_Nevents
    group_id["size"] = rsa_result.size
    group_id["seed_offset"] = rsa_result.seed_offset

    # Close the file
    close(hdf5_id)
    
end

# A function to read RSA results information
function read_rsa_results(hdf5_file, generation, Nmolecules, Ngrids)
    
    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * outputfile_path)
        error("Output File Error")
    end

    # Open the file
    hdf5_id = h5open(hdf5_file, "r")

    # Read the number of performed runs
    main_id = hdf5_id["run-info"]["generation-"*string(generation)]
    NRuns = read(main_id, "Nruns") 

    # Close the file
    close(hdf5_id)

    # Allocate a resutls vector
    rsa_results = Vector{rsa_run_results_struct}(undef, NRuns)

    # Read every rsa run from the hdf5 file
    for run_id in 1:NRuns
        rsa_results[run_id] = read_hdf5_rsa_run(hdf5_file, generation, run_id, Nmolecules, Ngrids)    
    end

    # Return the results
    return rsa_results

end

function read_hdf5_rsa_run(hdf5_file, generation, run_id, Nmolecules, Ngrids)

    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * outputfile_path)
        error("Output File Error")
    end

    # Open the file
    hdf5_id = h5open(hdf5_file, "r")

    # Get the correct group
    group_id = hdf5_id["run-info"]["generation-"*string(generation)]["rsa-run-"*string(run_id)]

    # Generate the results struct
    rsa_result = rsa_run_results_struct()

    # Read all information
    rsa_result.randomseed = read(group_id, "randomseed")
    rsa_result.status = read(group_id, "status")
    rsa_result.Nsteps = read(group_id, "Nsteps") 
    rsa_result.stepinfo = read(group_id, "stepinfo")
    tmp_Nevents = read(group_id, "Nevents")
    rsa_result.size = read(group_id, "size")
    rsa_result.seed_offset = read(group_id, "seed_offset")

    # Transform tmp_Nevents
    rsa_result.Nevents = Matrix{Vector{Int64}}(undef, Nmolecules, Ngrids)
    counter = 0
    for molecule_id in 1:Nmolecules
        for grid_id in 1:Ngrids
            counter += 1
            rsa_result.Nevents[molecule_id, grid_id] = tmp_Nevents[1:4, counter]
        end
    end

    # Close the file
    close(hdf5_id)

    # Return results
    return rsa_result
    
end


"""

    read_hdf5_output_file(hdf5_file::String, generation::Int64)

Reads and returns all information of RSA simulations within a generation from a HDF5 file found under the given path `hdf5_file`.

# Return values
Returns input information and results as structs in the follwing order:
- `rsa_results`: Vector storing all results of the RSA simulations. Every vector entry is a rsa\\_run\\_results_struct struct containing all information for a **single** RSA run. 
- `Nmolecules`: Total number of molecule types used.
- `molecules`: Vector storing all information concerning the molecule types. Every vector entry is a molecule_struct struct containing all information for a **single** molecule type.
- `Ngrids`: Total number of grid types used.
- `grids`: Vector storing all information concerning the grid types. Every vector entry is a grid_struct struct containing all information for a **single** grid type.
- `lattice`: A lattice_struct containing all information of the used lattice.
- `events`: A events_struct containing all information of the events and general RSA settings.
"""
function read_hdf5_output_file(hdf5_file, generation)

    # Check whether the file already exists
    if ! isfile(hdf5_file)
        println("The following HDF5 file does not exist: " * outputfile_path)
        error("Output File Error")
    end

    # Read input information
    Nmolecules, molecules, Ngrids, grids, lattice, events = read_hdf5_input_information(hdf5_file, generation)

    # Read RSA results
    rsa_results = read_rsa_results(hdf5_file, generation, Nmolecules, Ngrids)

    # Return results
    return rsa_results, Nmolecules, molecules, Ngrids, grids, lattice, events
    
end
